#
#    Copyright 2014-2015
#
#      STIC - Universidad de La Laguna (ULL) <gesinv@ull.edu.es>
#
#    This file is part of Modelado de Servicios TIC.
#
#    Modelado de Servicios TIC is free software: you can redistribute it and/or modify it under
#    the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Modelado de Servicios TIC is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with Modelado de Servicios TIC.  If not, see
#    <http://www.gnu.org/licenses/>.
#

desc "Ejecutar la aplicacion en Firefox"
task :runapp do
  sh "python ejecutable.py"
  sh "python manage.py runserver &"
  sh "firefox localhost:8000 &"
end

desc "Iniciar servidor"
task :server do
  sh "python manage.py runserver"
end

desc "Volver a generar las paginas"
task :recargar do
  sh "python ejecutable.py"
end

desc "Parar el servidor"
task :stopserver do
  sh "killall python"
end

desc "Ejecutar el modulo upload"
task :upload do
  sh "python ejecutable.py"
  sh "python manage.py runserver &"
  sh "firefox localhost:8000/uploads &"
end

desc "Ejecutar los test"
task :test do
  sh "python test_unittest.py Archi_Test.archimate"
  sh "python test_selenium.py"
end

desc "Comprobar Sondas"
task :sonda do
  sh "python sondas.py"
end

desc "Generar fichero KML de sondas"
task :maps do
  sh "python maps.py"
end
