desc "Generar paginas e Iniciar servidor"
task :runapp do
  sh "python ejecutable.py Archi_Stic2.0.archimate"
  sh "python manage.py runserver 8001"
end

desc "Iniciar servidor"
task :server do
  sh "python manage.py runserver"
end

desc "Vuelve a generar las paginas"
task :recargar do
  sh "python ejecutable.py Archi_Stic2.0.archimate"
end
